### PR TITLE
fix travis script typo

### PR DESCRIPTION
**Pull request by dimalev**

### CODE REVIEW

**Comment by dimalev** [comment]
there are planty of jshint errors during build invocation. what politics should be used to fix those ? for example i am not a fan of ===. should this test be switched off or fixed in code ?

**Comment by stritti** [comment]
Hi @dimalev ,

Many thanks for your support to fix the scripts. Probably we could disable the test in first step and postpone the improved style?

**Comment by stritti** [comment]
@dimalev currently at your Pullrequest the file bower.json could not be found by bower. Do you have an idea why?

**Comment by dimalev** [comment]
yes, i am working on it

**Comment by stritti** [comment]
really great. Thanks a lot for your support.

**Comment by dimalev** [comment]
so, it kinda works

as i understand - it creates bundles for you, but those are not published anywhere, so it just checks that "it builds successfuly"

what about porting js part of project to somehow pure nodejs ?

**Comment by stritti** [comment]
You thjink about proting log4js? There is already a forked port at log4js-node on GitHub.
Or do you want to change the build environment? I originally came from Java and would be pleased for any support to improve log4js!

**Comment by dimalev** [comment]
java is kool
yes, i think about changing build environment. javascript tests in java enviroment look .... fun :)

what do you think about adding some kind of solr log4js handlers' configurations and tutorials how to use those ? should be lots of fun :)

**Comment by stritti** [comment]
Hi @dimalev ,

that would be really good to build the JavaScript part with JS-Tools. Years ago ther were no such tools for that.
If you are interessted in doing more at the project I would invite you to improve it. 

Regards from Germany,

Stephan

**Pull request merged**
